import { z } from 'zod';
import { timestampSchema } from './vehicle';

export const driveLogSchema = z.object({
    organizationId: z.string(),
    vehicleId: z.string(),
    vehicleName: z.string().optional(),
    vehicleDisplayName: z.string().optional(),
    driverUid: z.string(),
    driverName: z.string().optional(),
    date: z.string().optional(),
    timestamp: timestampSchema,
    startKm: z.number(),
    endKm: z.number(),
    distance: z.number().optional(),
    startTime: z.string().optional(),
    endTime: z.string().optional(),
    purpose: z.string().optional(),
    destination: z.string().optional(),
    startLocation: z.string().optional(),
    passengers: z.number().optional(),
    vehicleType: z.string().optional(),
    passengerCount: z.number().optional(),
    passengerNames: z.array(z.string()).optional(),
    notes: z.string().optional(),
    fuelAmount: z.number().optional(),
    energyCost: z.number().optional(),
    batteryStart: z.number().optional(),
    batteryEnd: z.number().optional(),
    isRetroactive: z.boolean().optional(),
    isIncomplete: z.boolean().optional(),
    reservationId: z.string().optional(),
    inputMethod: z.enum(['ocr', 'manual', 'favorite']).optional(),
    createdAt: timestampSchema.optional(),
    editedAt: timestampSchema.optional(),
    expiresAt: timestampSchema.optional(),
});
