import { z } from 'zod';
import { timestampSchema } from './vehicle';

export const driveLogSchema = z.object({
    organizationId: z.string().catch(''),
    vehicleId: z.string().catch(''),
    vehicleName: z.string().optional().catch(undefined),
    vehicleDisplayName: z.string().optional().catch(undefined),
    driverUid: z.string().catch(''),
    driverName: z.string().optional().catch(undefined),
    date: z.string().optional().catch(undefined),
    timestamp: timestampSchema.catch(() => new Date()),
    startKm: z.coerce.number().catch(0),
    endKm: z.coerce.number().catch(0),
    distance: z.coerce.number().optional().catch(undefined),
    startTime: z.string().optional().catch(undefined),
    endTime: z.string().optional().catch(undefined),
    purpose: z.string().optional().catch(undefined),
    destination: z.string().optional().catch(undefined),
    startLocation: z.string().optional().catch(undefined),
    passengers: z.coerce.number().optional().catch(undefined),
    vehicleType: z.string().optional().catch(undefined),
    passengerCount: z.coerce.number().optional().catch(undefined),
    passengerNames: z.array(z.string()).optional().catch(undefined),
    notes: z.string().optional().catch(undefined),
    fuelAmount: z.coerce.number().optional().catch(undefined),
    energyCost: z.coerce.number().optional().catch(undefined),
    // 하이패스 사용 정보 (운행일지 저장 시 선택적으로 기록 — PDF/Excel '하이패스 포함' 출력에 사용)
    hipassCardNumber: z.string().optional().catch(undefined),
    hipassBalanceBefore: z.coerce.number().optional().catch(undefined),
    hipassBalanceAfter: z.coerce.number().optional().catch(undefined),
    batteryStart: z.coerce.number().optional().catch(undefined),
    batteryEnd: z.coerce.number().optional().catch(undefined),
    isRetroactive: z.boolean().optional().catch(undefined),
    isIncomplete: z.boolean().optional().catch(undefined),
    isManuallyCorrected: z.boolean().optional().catch(undefined),
    originalStartKm: z.coerce.number().optional().catch(undefined),
    reservationId: z.string().optional().catch(undefined),
    inputMethod: z.enum(['ocr', 'manual', 'favorite']).optional().catch(undefined),
    createdAt: timestampSchema.optional().catch(undefined),
    editedAt: timestampSchema.optional().catch(undefined),
    expiresAt: timestampSchema.optional().catch(undefined),
});
